services:
  server:
    image: .
    ports:
      - "3000:3000"

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"